# This file was generated by ChatGPT.

param (
    [string]$ConfigPath = ".vscode/c_cpp_properties.json",
    [string]$ConfigName = ""
)

if (!(Test-Path $ConfigPath)) {
    Write-Error "Cannot find $ConfigPath"
    exit 1
}

# Load VS Code config
$json = Get-Content $ConfigPath -Raw | ConvertFrom-Json
$configs = $json.configurations

if ($ConfigName) {
    $config = $configs | Where-Object { $_.name -eq $ConfigName }
    if (!$config) {
        Write-Error "Configuration '$ConfigName' not found."
        exit 1
    }
} else {
    $config = $configs[0]
}

$compiler = $config.compilerPath
$includes = $config.includePath
$defines  = $config.defines
$cStd     = $config.cStandard
$extraArgs = $config.compilerArgs

if (!(Test-Path $compiler)) {
    Write-Error "Compiler not found: $compiler"
    exit 1
}

Write-Host "Using compiler: $compiler"
Write-Host "Configuration: $($config.name)"
Write-Host ""

# Detect compiler type
$compilerName = Split-Path $compiler -Leaf
$isMSVC = $compilerName -match "^cl(\.exe)?$"

# Build common args
$includeArgs = @()
foreach ($i in $includes) {
    $includeArgs += if ($isMSVC) { "/I$i" } else { "-I$i" }
}

$defineArgs = @()
foreach ($d in $defines) {
	$sd = if ($isMSVC) { "/D$d" } else { "-D$d" }
	if ($d -match '\s') {
        # Quote defines containing spaces
        $sd = '"' + $sd.Replace('"', '\"') + '"'
    }
    $defineArgs += $sd
}

$stdArg = if ($cStd) {
    if ($isMSVC) { "" } else { "-std=$cStd" }
}

# Compiler-specific analysis flags
if ($isMSVC) {
    $analysisFlags = @(
        "/nologo",
        "/Zs",        # syntax check only
        "/W4"         # warnings
    )
} else {
    $analysisFlags = @(
        "-fsyntax-only"
    )
}

# Find C files
$cFiles = Get-ChildItem -Recurse -Filter "*.c"

if ($cFiles.Count -eq 0) {
    Write-Warning "No .c files found."
    exit 0
}

$hadErrors = $false

foreach ($file in $cFiles) {
    Write-Host "Analyzing $($file.FullName)"

    $args = @()
    $args += $analysisFlags
    $args += $includeArgs
    $args += $defineArgs
    if ($stdArg) { $args += $stdArg }
    if ($extraArgs) { $args += $extraArgs }
    $args += $file.FullName


	Write-Host $compiler $args
    $proc = Start-Process `
        -FilePath $compiler `
        -ArgumentList $args `
        -NoNewWindow `
        -PassThru `
        -Wait

    if ($proc.ExitCode -ne 0) {
        $hadErrors = $true
		break
    }
}

if ($hadErrors) {
    Write-Error "Analysis completed with errors."
    exit 1
} else {
    Write-Host "Analysis completed successfully."
}
