#ifndef _RACE_MAPOBJ_ENEMIES_ALL_H
#define _RACE_MAPOBJ_ENEMIES_ALL_H

#include "boss.h"
#include "cheep_cheep.h"
#include "crab.h"
#include "mole.h"
#include "eyerock.h"
#include "fireball2.h"
#include "flipper.h"
#include "goomba.h"
#include "ironBall.h"
#include "mkdEfBubble.h"
#include "mkdEfBurner.h"
#include "moveTree.h"
#include "nsKiller1.h"
#include "nsKiller2.h"
#include "obPakkunSf.h"
#include "piranha_plant.h"
#include "piranha_plant_fire.h"
#include "podoboo.h"
#include "pokey.h"
#include "swoop.h"
#include "thwomp.h"
#include "snowman.h"
#include "sun.h"
#include "sunFireSnake.h"
#include "traffic.h"

#endif // _RACE_MAPOBJ_ENEMIES_ALL_H
